### ISSUE TITLE
Value for account in your example

### ISSUE THREAD

**Issue by thedavegray** [panoramicdata/ServiceNow.Api#18]
Hello

In your code example you show three arguments to the console application; account, username and password. 

`var account = args[0];`

Can I ask what this form this value you should be?  I assumed it was the domain https://mycompany.service-now.com but this is not correct. 

I have tried with 

-  https://mycompany.service-now.com
-  https://mycompany.service-now.com/api/now/table/

I know my domain, user and pass are correct as I can query using Postman. 

But get this "{"_No such host is known. (https:443_)"}"

Be grateful for any advice as quite under the cosh to get this done :-(

**Comment by thedavegray** [comment]
Ah ok, so looking at the class/method `ServiceNowClient` 

it's just your company name 

`string uriString = ((_options.Environment != ServiceNowEnvironment.GCC) ? ("https://" + account + ".service-now.com") : ("https://" + account + ".servicenowservices.com"));`

Not entirely sure why docs could simply state that.

**Comment by rolandbanks** [comment]
So it's all working?
